### ISSUE TITLE
Implement Security

### ISSUE THREAD

**Issue by hloydl** [camunda/camunda-bpm-graphql#1]

**Comment by mark-james** [comment]
Hi Harald,
I'm not sure if you've done anything on this yet, but I've created a servlet filter modelled/reusing logic found in the camunda engine-rest project. It works with the camunda basic authentication implementation.

Do you want it?

cheers
Mark

**Comment by hloydl** [comment]
Hi Mark, I haven't worked on security here, so yes, sure, I am interested in your servlet filter :-)

**Comment by mark-james** [comment]
No problem. Will create a pull request in the next day or two for you to review.

**Comment by hloydl** [comment]
👍

**Comment by mark-james** [comment]
I've just created a pull request for you to review.

**Comment by herr-vogel** [comment]
#6

**Comment by hloydl** [comment]
closed
