### ISSUE TITLE
Camunda GraphQL Release 0.2.0

### ISSUE THREAD

**Issue by hloydl** [camunda/camunda-bpm-graphql#20]
release version: 0.2.0
next dev version: 0.3.0-SNAPSHOT

**Comment by ThorbenLindhauer** [comment]
0.2.0 is released, see https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/graphql/camunda-bpm-graphql/0.2.0/. Should also be on Maven central after some sync time. Sorry once again for the delay.
