### ISSUE TITLE
GraphiQL: index.html - replace cdn references with locally hosted js/css-files

### ISSUE THREAD

**Issue by hloydl** [camunda/camunda-bpm-graphql#21]
do not download these 6 files but host them locally :  
  
    <script src="//cdn.jsdelivr.net/es6-promise/4.0.5/es6-promise.auto.min.js"></script>
    <script src="//cdn.jsdelivr.net/fetch/0.9.0/fetch.min.js"></script>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react.min.js"></script>
    <script src="//cdn.jsdelivr.net/react/15.4.2/react-dom.min.js"></script>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/graphiql@0.11.3/graphiql.css" />
    <script src="//cdn.jsdelivr.net/npm/graphiql@0.11.3/graphiql.js"></script>

**Comment by hloydl** [comment]
This issue is solved with using graphiql-spring-boot-starter

**Comment by hloydl** [comment]
Todo: remove https://github.com/camunda/camunda-bpm-graphql/blob/dev-2017-09/src/main/webapp/graphql/index.html and other related files

**Comment by herr-vogel** [comment]
[fixed](https://github.com/camunda/camunda-bpm-graphql/commit/4452c4ea5259a47b088e8db361d9d29eada3ca0a)
