### ISSUE TITLE
Camunda GraphQL Release 0.3.0

### ISSUE THREAD

**Issue by hloydl** [camunda/camunda-bpm-graphql#26]
please release from master branch :-)

release version: 0.3.0
next dev version: 0.4.0-SNAPSHOT

**Comment by menski** [comment]
The artifacts can be found on the [Camunda nexus](https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/graphql/camunda-bpm-graphql/0.3.0/) and should show up on maven central after a while.
