### ISSUE TITLE
rename repo to camunda-bpm-graphql

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-graphql#3]
we have naming convention for extensions ... I got used to have everything starting with "camunda-bpm-" ... maybe its a good idea to change this repo before it gets "too big to change"?

**Comment by hloydl** [comment]
@ThorbenLindhauer, can you rename this repo to camunda-bpm-graphql (I do not have the access rights to do so)

**Comment by ThorbenLindhauer** [comment]
Done.
