### ISSUE TITLE
Unclear installation instructions - is there a Docker image?

### ISSUE THREAD

**Issue by davie-robertson** [camunda/camunda-bpm-graphql#31]
This look like a great product that we plan to use as a remote schema with the Hasura GraphQL server (https://hasura.io).  

I currently have the Camunda running using the Docker image and it isn't clear from this repo's documentation which steps are mandatory and which are optional - for example do we really need to build the GraphQL server or can we just grab the `.war` from the repo (which seems to require another steps `This maven2 hosted repository is not directly browseable at this URL.`).

I've read the dev thread - and the last post there is pretty similar to my questions - https://forum.camunda.org/t/developing-the-camunda-graphql-extension/2872/36

The best/easiest approach would be a docker container with the GraphQL code in there - do you know if this has been done?

TIA

D.

**Comment by mmaico** [comment]
The version 0.4.0(will be released in the next few days) can be use in the Docker Image. This version work embbeded in the Camunda Spring Boot.
