### ISSUE TITLE
Move classes to camunda extension package namespace

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-bpm-graphql#5]
Classes should be in subpackages of `org.camunda.bpm.extension`.

**Comment by herr-vogel** [comment]
Hey @ThorbenLindhauer I moved it to the right subpackage.

**Comment by hloydl** [comment]
Hallo Dani,

hmm, schau mal unter
https://github.com/camunda/camunda-bpm-graphql/tree/master/src/main/java/graphql/servlet

ich sehe es gerade nicht...(das subpackage)


2017-03-27 17:00 GMT+02:00 Daniel Vogel <notifications@github.com>:

**Comment by hloydl** [comment]
fixed with commit https://github.com/camunda/camunda-bpm-graphql/commit/0eb29d2146187d902857b2485465a418fb764147
