### ISSUE TITLE
Waiting for Camunda

### ISSUE THREAD

**Issue by mmaico** [camunda/camunda-bpm-graphql#50]
Hi @celanthe, i changed the version to release. 
Only jar camunda-bpm-graphql should be in Maven Central.

Thanks ;)

**Comment by celanthe** [comment]
Hi @mmaico -- I just cut a new release, and will keep an eye on the GitHub Actions workflow to ensure everything goes smoothly. If you can take a look once the Action has finished running as well, I would much appreciate it!

**Comment by mmaico** [comment]
Hi @celanthe  all actions were executed successfully but still not showing up in Maven Central :(

**Comment by celanthe** [comment]
Hi @mmaico -- I'll take a look into this and see what's happening. I'll circle back ASAP once I have an answer! :)

**Comment by celanthe** [comment]
Hi @mmaico Just wanted to circle back. I haven't forgotten about you. I've opened a few PRs for fixes to the POM files and the workflow YAML itself that I hope will lead to us resolving this issue and remediate outdated documentation at the same time. I hope this helps. My PR #53 has a failing build currently, and I will debug that ASAP. :) 

Thank you again for your contributions to Camunda. We truly appreciate it!

**Comment by mmaico** [comment]
Hi @celanthe, I'm looking forward to seeing the release of this version on Maven Central. I'm working in other features and soon i open the new pull request. Thanks!!!

**Comment by mmaico** [comment]
Hi @celanthe can i help you in this task?

**Comment by celanthe** [comment]
Hi @mmaico -- I merged a few pull requests that I thought might resolve this issue, but sadly I'm still not seeing the release on our side. I'm going to reach out to our Infrastructure team and ask them if they have any advice as to what may be occurring here, because as far as I can see, the deploy.YML workflow ran successfully. 

Apologies for the delay in response, I was out of office for some time recovering from a medical procedure!

**Comment by berndruecker** [comment]
I can look into this

**Comment by berndruecker** [comment]
The maven distribution settings where overwritten in the pom: https://github.com/camunda-community-hub/camunda-platform-graphql/commit/0a82dfb14bf835c7f0c8b96e7c03f6e3ca7ed57d. Works now - I create a new release that's also pushed to Maven Central: https://github.com/camunda-community-hub/camunda-platform-graphql/releases/tag/0.4.2
