### ISSUE TITLE
Rename extension, update assets & documentation

### ISSUE THREAD

**Issue by celanthe** [camunda/camunda-bpm-graphql#59]
Hi Marcelo,

I hope today finds you well! This issue is being opened to ask if you would be open to renaming your extension on GitHub to reference Camunda Platform 7 rather than Camunda BPM after its release on April 12th, 2022. (For example: camunda-platform-7-graphql) This change will also likely impact any screenshots you have in the README that reference Camunda BPM or previous versions of Camunda Platform, and this will likely need to also be updated throughout the repo's documentation as a whole. You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with. 

While it is not a **requirement** that you rename your extension to align with Camunda Platform 7, we would **greatly** appreciate it if you could make these changes, and merge them anytime after April 12th, 2022.

 if you have any questions or require any assistance, please do not hesitate to reach out to @camunda-community-hub/devrel! :)

**Comment by mmaico** [comment]
Hi @celanthe, i'm great ;)

I'll make these changes and i'll let you know when i'm done.

**Comment by mmaico** [comment]
@celanthe the changes were made in this pull request: https://github.com/camunda-community-hub/camunda-platform-graphql/pull/60

**Comment by akeller** [comment]
Hi @mmaico, Rin has moved on from Camunda. I'll see if we can get another reviewer to take a look at these changes. Thanks!

**Comment by berndruecker** [comment]
Awesome - thank you so much @mmaico. I merged the PR and also renamed the repo to "https://github.com/camunda-community-hub/camunda-platform-7-graphql" (which should not change anything as everything gets redirected). That was quick!

**Comment by berndruecker** [comment]
I will further adjust the readme to

- properly refer to C7
- refer to the new group id on artifactory

**Comment by berndruecker** [comment]
See https://github.com/camunda-community-hub/camunda-platform-7-graphql/blob/main/README.md.

I would suggest releasing a 0.5.0 that then will have the new package/artifact id. OK @mmaico?

**Comment by mmaico** [comment]
@berndruecker I had thought the same thing

**Comment by mmaico** [comment]
@berndruecker i saw that the other projects didn't change the groupid nor the artifactid was this necessary?

**Comment by berndruecker** [comment]
@mmaico  Nothing is "necessary" in this sense. I think it is a very decent change though. Then I will go ahead and release 0.5.0 - or WDYT?

**Comment by mmaico** [comment]
Done!
