### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-bpm-graphql#7]
Are there any plans for a first (alpha) release yet? Could be nice to show people the potential of GraphQL in the Camunda context. The feature set is in my opinion of secondary interest for a first release.

**Comment by hloydl** [comment]
Hi Thorben, 
Good point. 
First we would like to show an **application** of the Camunda GraphQL server. 
Actually we are preparing a Tasklist based on Camunda GraphQL. 

Basically the goals are: 
- freedom to choose the GUI library you prefer to build Camunda client apps 
- get JavaScript GUI people on board to build cool Camunda client apps using e.g. node.js and Angular/React/whatever...
- show how easy it is to build Camunda client apps
- provide examples, tools, etc.

From Camundas perspective and the Community Extension: What would you want us to achieve to make it "alpha-ready"?

**Comment by ThorbenLindhauer** [comment]
Hi Harald,

Thanks for sharing your plans. The time when and what you release is up to you. In that sense, I don't *want* (in the sense of demanding) you to achieve anything. Yet, I would like to give advice.

Based on Camunda's and my experience, with regular releases and accompanying blog posts, you can attract people who are interested in using and maybe also contributing to the extension. Users get an idea what the goal of the project is (even if that goal hasn't been reached yet), they see that progress is being made, and they can provide feedback. I personally prefer this to a big-bang release in a far future (given I don't know in which time you plan reach the feature set you mention above), where it's maybe not even clear that it will see the light of day.

For example, a first release could contain the current state plus some short introduction on how to deploy the extension and make requests with one of the GraphQL clients. This would likely be exiting enough to attract people who have never heard of GraphQL before (like me when I read your forum post for the first time).

Lastly, making a release is really cheap for us. Just ping @hawky-4s-. He'll hit the Jenkins release button and later publish the release to Maven central. There is not much effort and risk involved.

In the end, it's up to you and I'm fine if you want to keep developing more thing before you release the first time :)

Cheers,
Thorben

**Comment by hloydl** [comment]
We are working on this. Expect something released here in the next two weeks :-)

**Comment by meyerdan** [comment]
When will this extension be released?

**Comment by hloydl** [comment]
In the next two weeks :-)

**Comment by hloydl** [comment]
Hi @hawky-4s- 

can you release the current Version as Alpha Version? 
I do not know what steps you guys have to perform - @ThorbenLindhauer told be I just have to "ping" you ;-)

Harald

**Comment by ghost** [comment]
Hi Harald,

Sorry for being late but Camunda had their hackdays 2017 and I was occupied.
I released your project a few minutes ago, also on Maven Central, as 0.1.0-alpha1.
It should pop up after a few hours under the following link: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22camunda-bpm-graphql%22
I set the next development version back again to 0.1.0-SNAPSHOT.

In the future it is okay, when you just create an issue and assign it to me.
The content should be like
```
release version: 0.1.0
next dev version: 0.2.0-SNAPSHOT
```

Cheers,
Christian
